### ISSUE TITLE
Screenshots missing in repository

### ISSUE THREAD

**Issue by rinigus** [black-sheep-dev/harbour-sailhub#113]
While screenshots are referred to in YAML (https://github.com/black-sheep-dev/harbour-sailhub/blob/main/rpm/harbour-sailhub.yaml#L25), they are missing at specified URLs. Was just a corresponding commit missing or it is a placeholder for future?

**Comment by black-sheep-dev** [comment]
Only missed to add the images to repository.
The links was missing the branch too.

**Comment by rinigus** [comment]
That's right, URL has branch missing as well. Well, as soon as you fix it, I can trigger new builds at OBS. Even without tagging at GitHub it will look nicer in Chum GUI

**Comment by black-sheep-dev** [comment]
Fixed

**Comment by rinigus** [comment]
Builds triggered. As soon as it is published and I will manage to check it in GUI, I will close it here

**Comment by rinigus** [comment]
Builds done and all is visible in GUI. Looking good!

Closing over here

**Comment by rinigus** [comment]
PS: Closed in SailHub :)
