### ISSUE TITLE
App doesn't show Chinese translation

### ISSUE THREAD

**Issue by dashinfantry** [black-sheep-dev/harbour-sailhub#29]
I installed the newest version.

**Comment by black-sheep-dev** [comment]
Hi, thanks for the report.
Did it work in the previous version?
The data and RPM package looks OK for me...

**Comment by dashinfantry** [comment]
Both not available-------- 原始邮件 --------发件人： Samuel Kron ***@***.***>日期： 2021年4月10日周六 22:07收件人： black-sheep-dev/harbour-sailhub ***@***.***>抄送： dashinfantry ***@***.***>, Author ***@***.***>主    题： Re: [black-sheep-dev/harbour-sailhub] App doesn't show Chinese translation (#29)
Hi, thanks for the report.
Did it work in the previous version?
The data and RPM package looks OK for me...

**Comment by black-sheep-dev** [comment]
Is your device locale zh_Hans?

**Comment by dashinfantry** [comment]
My device has Chinese-------- 原始邮件 --------发件人： Samuel Kron ***@***.***>日期： 2021年4月10日周六 23:45收件人： black-sheep-dev/harbour-sailhub ***@***.***>抄送： dashinfantry ***@***.***>, Author ***@***.***>主    题： Re: [black-sheep-dev/harbour-sailhub] App doesn't show Chinese translation (#29)
Is your device locale zh_Hans?

**Comment by dashinfantry** [comment]
Chinese zh_CN is 简体中文（中国大陆）in Sailfish OS languages settings.

**Comment by black-sheep-dev** [comment]
Can you please try to rename /usr/share/harbour-sailhub/translations/harbour-sailhub-zn_Hans.qm to harbour-sailhub-zh_CN.qm and try if this works for you?

**Comment by dashinfantry** [comment]
I can't rename it because Sailfish 4 can't use patch now.But other apps which show Chinese named XXX-zh_CN.qm

**Comment by black-sheep-dev** [comment]
I will fix this in the next release

**Comment by black-sheep-dev** [comment]
New release is out. Please check if it works now.

**Comment by dashinfantry** [comment]
It displays Chinese now.

**Comment by black-sheep-dev** [comment]
Good to hear. Thank you for your translation!
